notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

env:
 - CC=gcc

sudo: false

addons:
 apt:
  packages:
   - build-essential
   - autoconf
   - curl
   - libcurl4-openssl-dev
   - zlib1g-dev
   - libncurses5-dev
   - libpstreams-dev
   - unzip

language: perl

perl:
 - "5.22"

install:
 - git clone --depth 1 --single-branch --branch dev https://github.com/cancerit/alleleCount.git
 - cd alleleCount
 - ./setup.sh $HOME/wtsi-opt
 - cd ../
 - rm -rf alleleCount

script:
 - export LD_LIBRARY_PATH=$HOME/wtsi-opt/lib
 - build/htstools.sh $HOME/wtsi-opt
 - ./setup.sh $HOME/wtsi-opt
